# values.yaml

# Frontend Configuration
zauni-zadanie-2024-frontend:
  replicaCount: 1
  apiHost: "127.0.0.1"
  image:
    repository: morgrotsk/zauni-zadanie-appfrontend-2024
    tag: 1.0.0
  service:
    nodePort: 30080
    targetPort: 8080
    port: 8080

# Backend Configuration
zauni-zadanie-2024-backend:
  replicaCount: 1
  image:
    repository: morgrotsk/zauni-zadanie-appbackend-2024
    tag: 1.0.0
  service:
    targetPort: 9080
    port: 9080
  env:
    MONGO_USERNAME: "admin"
    MONGO_PASSWORD: "password"
    MONGO_AUTH_SOURCE: "platformsdb"

  mongodb:
    auth:
      rootPassword: "YourStrongRootPassword"
      username: "admin"
      password: "password"
      database: "platformsdb"
    service:
      type: ClusterIP
    persistence:
      enabled: false
    initdbScripts:
      init_script.js: |
        db = db.getSiblingDB("platformsdb");
        db.createUser({
          user: "admin",
          pwd: "password",
          roles: [{ role: "readWrite", db: "platformsdb" }],
        });
        db.createCollection("platforms");
        db.platforms.insertMany([
          {
            name: "openshift",
            codedetail: {
              usecase: "Container platform",
              rank: 12,
              homepage: "https://openshift.com",
              download:
                "https://developers.redhat.com/products/codeready-containers/overview",
              votes: 0,
            },
          },
          {
            name: "kubernetes",
            codedetail: {
              usecase: "Container orchestration platform ",
              rank: 38,
              homepage: "https://kubernetes.com",
              download: "https://kubernetes.io/docs/tasks/tools/install-minikube/",
              votes: 0,
            },
          },
          {
            name: "rancher",
            codedetail: {
              usecase: "Container platform management ",
              rank: 50,
              homepage: "https://rancher.com/",
              download: "https://github.com/rancher/rancher",
              votes: 0,
            },
          },
        ]);
