apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-backend" (include "app.name" .) }}
spec:
  selector:
    app: {{ printf "%s-backend" (include "app.name" .) }}
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: {{ .Values.backend.service.targetPort }}
      protocol: TCP
  type: LoadBalancer
