# templates/frontend-service.yaml

apiVersion: v1
kind: Service
metadata:
  name: {{ printf "%s-frontend" (include "app.name" .) }}
spec:
  selector:
    app: {{ printf "%s-frontend" (include "app.name" .) }}
  ports:
    - port: {{ .Values.frontend.service.port }}
      targetPort: {{ .Values.frontend.service.targetPort }}
      nodePort: {{ .Values.frontend.service.nodePort }}
      protocol: TCP
      name: http
  type: LoadBalancer 