apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ printf "%s-frontend" (include "app.name" .) }}
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: {{ printf "%s-frontend" (include "app.name" .) }}
  template:
    metadata:
      labels:
        app: {{ printf "%s-frontend" (include "app.name" .) }}
    spec:
      containers:
        - name: frontend
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          ports:
              - containerPort: {{ .Values.frontend.service.targetPort }}
          env:
            - name: REACT_APP_APIHOSTPORT
              value: {{ .Values.frontend.apiHost }}:{{ .Values.backend.service.port }}
